title: "<title>"
body:
- type: dropdown
  attributes:
    description: What would you like to discuss?
    options:
      - "Product Feedback"
      - "Question"
      - "Bug"
      - "Show & Tell"
      - "General"
  validations:
    required: true
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true
